import Container from '@mui/material/Container'
import Box from '@mui/material/Box'
import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from '../src/components/SearchBar'
import { purple } from '@mui/material/colors'
import Filters from '../src/containers/Filters'
import DataTable from '../src/components/DataTable'
import { transactions } from '../src/data/mock_transactions'
import { ITransactions } from '../src/types'

const columns = ['Transaction_name', 'Amount', 'Category', 'Transaction_vendor']

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Advanced Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          p: 1,
          m: 1,
          backgroundColor: purple[200],
          borderRadius: 1,
          width: '70%',
          margin: 'auto',
          height: '400px'
        }}
      >
        <h2 className='searchHeaders'>Search Transactions</h2>
        <SearchBar />
        <Filters />
      </Box>
      <DataTable columns={columns} rows={transactions} />
    </Container>
  )
}

export default Home
